# Generated by Django 2.2.5 on 2019-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbanner_productsku_promotionpc_typeshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpc',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已过期')], default=0, verbose_name='活动状态'),
        ),
    ]
