# Generated by Django 2.2.5 on 2019-09-29 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_promotionpc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbanner',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='promotionpc',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='promotionpc',
            name='update_time',
        ),
        migrations.AddField(
            model_name='productbanner',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='productbanner',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='productbanner',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='products',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='products',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='promotionpc',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='promotionpc',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='promotionpc',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='typeshow',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='typeshow',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='typeshow',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
